### PR TITLE
Preprocessing unused data

### LINKED ISSUE #1: Preprocess data to remove unused data
Since the data provided by PyPI contains a lot of information we don't need, such as the license or author, let's create a function that has:

- input: name of a package
- return: its version, size (in bytes), and its dependency spec.

For example:

- input: `scipy`
- return: `"1.5.4"`, `25879680`, `[<dependency numpy >=1.14.5 >]`

### PR DESCRIPTION
**Pull request by dinhanhx**
To resolve #1 
`preprocess.py` offers 3 methods
- `request_pkg_info(pkg_name, pkg_ver = '')` : just to get response json from pypi 
- `get_basic_info(pkg_info, filename='', requires_format=True)`: to preprocess response json 
-  `lazy_get_pkg(pkg_name, pkg_ver = '', filename='', requires_format=True)`: combine two functions.

The reason I kept two functions `request_pkg_info()` and `get_basic_info()` is for the case debugging, examining data, requesting data for other input or changing how the functions work.

It's recommended to use `lazy_get_pkg()` for other purposes.

Example:

```Python
import pprint
from preprocess import lazy_get_pkg

pkg_info = lazy_get_pkg('urllib3')
pprint.PrettyPrinter(indent=2).pprint(pkg_info)
```

Expected output:

```Python
{ 'name': 'urllib3',
  'requires_dist': [ ('brotlipy', [('>=', '0.6.0')]),
                     ('pyOpenSSL', [('>=', '0.14')]),
                     ('cryptography', [('>=', '1.3.4')]),
                     ('idna', [('>=', '2.0.0')]),
                     ('certifi', []),
                     ('ipaddress', []),
                     ( 'PySocks',
                       [('<', '2.0'), ('!=', '1.5.7'), ('>=', '1.5.6')])],
  'size': 136770}
```

### CODE REVIEW

**Review by Huy-Ngo — APPROVED** [review]

**Comment by Huy-Ngo** [comment]
Wait a minute, where do you get `136770` from? I checked 1.9 and 1.9.1; none of the distributions has this size.

**Comment by Huy-Ngo** [comment]
Ah I see, my JSON parser sort alphabetically so I see 1.19 as the latest while 1.26 should be the latest.

**Comment by Huy-Ngo** [comment]
It would be better if you can include the version in the return but ok

**Comment by Huy-Ngo** [comment]
Wait a minute, where is your checking for distribution?

**Comment by dinhanhx** [comment]
> Wait a minute, where is your checking for distribution?

By default `filename = ""`, `get_basic_info()` will get the first distribution in responded json. 
https://github.com/Huy-Ngo/dependency-size/blob/3ca8d1888f7a95e9a12222d0c14e9423574839cb/preprocess.py#L60-L65

`filename` is equivalent to distribution and I don't know how to parse this kind of pattern.

image

[Numpy 1.19.5](https://pypi.org/pypi/numpy/json)

**Comment by Huy-Ngo** [comment]
And that one you're viewing is the distribution for MacOS.

A simple way is to check if it has `linux` and `x86_64` or `amd64` in the string.

**Comment by dinhanhx** [comment]
> And that one you're viewing is the distribution for MacOS.
> 
> A simple way is to check if it has `linux` and `x86_64` or `amd64` in the string.

In reality, there are packages which don't have any specify distributions, for instance
image

[Urrlib3 1.26.1](https://pypi.org/pypi/urllib3/json)

That means when we only search `linux`, `x86_64`, `amd64`, nothing will be returned.

Pandas, numpy, ... specify distribution because (I guess) they have lower level languages or/and they use OS's libraries. Urllib3 doesn't because (I guess again) it uses native Python's libraries. 

To reduce work and not to focus on choosing distribution for specific system, I lazily get the first distribution

**Comment by Huy-Ngo** [comment]
So how do you verify that our work is true?

**Comment by dinhanhx** [comment]
> So how do you verify that our work is true?

Pick a package and a version => Open responded json data => Scroll to releases => Scroll to version => pick the first filename => Write down the size manually => Traverse the tree manually

Let @DDHLong do the test work

One test case since we don't do this for production

**Comment by Huy-Ngo** [comment]
On Mon, Jan 11, 2021 at 9:48 AM Dinh Anh Vu <notifications@github.com> wrote:

> Pick a package and a version => Open responded json data => Scroll to releases => Scroll to version => pick the first filename => Write down the size manually => Traverse the tree manually
>
> One test case since we don't do this for production

Alright then, you write the test cases*.

*: plural

**Pull request merged**
